"""create bot_data table.

Revision ID: a88181f12c99
Revises: b8d8eafb9ab7
Create Date: 2025-01-05 16:43:12.391676

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a88181f12c99"
down_revision: Union[str, None] = "b8d8eafb9ab7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bot_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("bot_data_id_check")),
        sa.PrimaryKeyConstraint("id", name=op.f("bot_data_pkey")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bot_data")
    # ### end Alembic commands ###
